A little fix, excluded servlet-api from that jsp dependency. you see, at runtime, it is properly overriden by the new api (3.1), but weld is fooled nevertheless, and tries to use a class from the old servlet-api, at least thats what I think happened ...
The NoSuchMethodError is avoided, but there's still the null pointer exception, which is probably caused by a logical error in my setup, will catch it at a deeper level, and look at the stack trace when I have the time.