added weld listner, which required jsp-api, there's still something wrong though, probably a version compatability issue, which is usually the case with NoSuchMethodError exceptions, I just have to figure out what's up ...  weld seems to work sometimes though, it successfully loads the com.app.injectedIn.RecieveInjection class, but fails to recursively load the injectee class, wonder why ...